### ISSUE TITLE
[FeatureRequest]Add a "Close all" command

### ISSUE THREAD

**Issue by ccsamzhao** [AkshaySG14/haystack-public#10]
If I open too many files, it will be tedious to close them one by one, especially the current close button on the canvas window is too small. So, I'd like to suggest adding a "Close all" command to close all opening editors.

**Comment by AkshaySG14** [comment]
Does close all editors suffice for your case? You can open up the command palette via CMD/CTRL+SHIFT+P and then access the command by searching it.
 
![Screenshot 2024-08-25 at 3 41 52 PM](https://github.com/user-attachments/assets/47c43db6-e6de-42fc-a9bb-5c5ae7b7fa95)
