### ISSUE TITLE
remote ssh is not working

### ISSUE THREAD

**Issue by andycjw** [AkshaySG14/haystack-public#13]
as titled, it will failed with following error

[17:19:06.119] Got request to download on client for {"artifact":"cli-alpine-x64","destPath":"/root/.haystack-editor/vscode-cli-e6aef4d6579e0318c4284970db9c36be63876c4a.tar.gz"}
[17:19:06.119] server download URL: https://update.code.visualstudio.com/commit:e6aef4d6579e0318c4284970db9c36be63876c4a/cli-alpine-x64/undefined
[17:19:06.119] Downloading VS Code server locally...
[17:19:06.375] Resolver error: Error: Failed to download VS Code Server (Server returned 404)

**Comment by fhyoga** [comment]
I have the same question.

**Comment by AkshaySG14** [comment]
Sorry we're working on this now. If you download the newest version of Haystack on non-Windows, you should be able to use PonySSH, but for now SSH won't work. We are actively working on this (along with WSL).

**Comment by mr-narender** [comment]
+1

is there a manual solution that could be used to deploy remote server and start it, that could help.

thanks btw.

**Comment by AkshaySG14** [comment]
If you are on Mac or Linux you can use the Pony SSH extension to perform SSH. Please let me know if you have issues/difficulties with this step. I can help guide you through it.

If you are on Windows please let me know as well

**Comment by mr-narender** [comment]
> If you are on Mac or Linux you can use the Pony SSH extension to perform SSH. Please let me know if you have issues/difficulties with this step. I can help guide you through it.
> 
> If you are on Windows please let me know as well

@AkshaySG14 I was testing it on windows to ssh to remote dev server (actually was trying on work laptop).

**Comment by AkshaySG14** [comment]
@mr-narender darn then I'll get moving on the new windows release ASAP

**Comment by mr-narender** [comment]
> @mr-narender darn then I'll get moving on the new windows release ASAP

@AkshaySG14 Thanks, appreciate quick turn up on this. let me know when you've fix ready, and I can do a quick test for you.

**Comment by andycjw** [comment]
same here, can help with the quick test

**Comment by ArkadiiKozlov** [comment]
+1, launch Haystack on Windows, trying to connect to Mint 20.1 vbox virtual machine on the same computer

(Standalone vs code under those conditions works OK)

**Comment by AkshaySG14** [comment]
For the folks here: we're still getting SSH fixed but for the time being does using another extension like Pony SSH work for y'all?

**Comment by mr-narender** [comment]
> For the folks here: we're still getting SSH fixed but for the time being does using another extension like Pony SSH work for y'all?

@AkshaySG14 

I haven't tried this one yet, may be I can try tomorrow on my workstation and let you know after.


**Update:**

I tried this PonySSH, and this seems to working.

**Comment by AkshaySG14** [comment]
OK this should finally be fixed. Please download the newest version of Haystack (v 0.16) off the website and LMK if this doesn't work!

**Comment by MuNeNiCK** [comment]
@AkshaySG14 
Remote SSH and WSL extensions worked fine with 0.16.
Thanks for your great work.
