### ISSUE TITLE
constant use of GPU even when idle

### ISSUE THREAD

**Issue by andycjw** [AkshaySG14/haystack-public#14]
it's using the GPU non stop even when not in focus, is this a malware trying to steal GPU compute time?

**Comment by AkshaySG14** [comment]
Hmm this shouldn't be happening. What OS are you using? This is what it looks like on Mac. It could be that we're the canvases suboptimallly. 

![Screenshot 2024-08-27 at 8 28 08 AM](https://github.com/user-attachments/assets/344de249-8bf5-4256-9441-d5aac20ce1aa)

**Comment by AkshaySG14** [comment]
Also RE: malware -- definitely not. I would chalk this up more to inexperience with the graphics libraries we're using (e.g. we have two canvases in Haystack). We are not a front for malware and would never do something shady like that.

**Comment by andycjw** [comment]
I'm using this on Windows, the GPU utilization is too high and something must be wrong
![image](https://github.com/user-attachments/assets/085c75eb-4335-4fc7-afba-d7ed758d9d82)

**Comment by clemisch** [comment]
I see similar behavior on Linux. One CPU core is always maxed out and there is significant GPU usage, even after several minutes of idleing.

**Comment by AkshaySG14** [comment]
Sorry to bother y'all, but could you try downloading this version and LMK if the issues are fixed: https://d2dv27o1k99orf.cloudfront.net/Haystack%20Editor%20Linux-test.zip?

**Comment by clemisch** [comment]
Thanks for the feedback. Unfortunately behavior is unchanged for me.

**Comment by AkshaySG14** [comment]
Oof. @clemisch do you know which Haystack process is causing the high CPU and GPU usage?

I have a couple of theories. Could you try:
1. Hiding canvas dots? Open the command palette (CTRL+SHIFT+P) and then search "hide canvas dots"
2. Deleting the canvases from Haystack? You need to use the developer console and manually delete the HTML elements. I've attached a video on this below.

https://github.com/user-attachments/assets/96ddb57d-3009-4a52-bcd2-198f07a4fa0f

**Comment by coljac** [comment]
> Sorry to bother y'all, but could you try downloading this version and LMK if the issues are fixed: https://d2dv27o1k99orf.cloudfront.net/Haystack%20Editor%20Linux-test.zip?

Still maxing out one core when idle.

**Comment by AkshaySG14** [comment]
@coljac that means it's not from one of the processes we spawn 🤔 . Did you try hiding the canvas dots or editing the DOM?

Alternatively, the issue could be that we're building Linux in a way that's causing performance issues.

**Comment by coljac** [comment]
> @coljac that means it's not from one of the processes we spawn 🤔 . Did you try hiding the canvas dots or editing the DOM?

Is it this? It does not seem to remove the dots for me.
![image](https://github.com/user-attachments/assets/527f2c18-801c-40c5-9bb7-98fe1d29f0b2)

**Comment by AkshaySG14** [comment]
Hmm weird it doesn't work through settings.

I have a couple of theories. Could you try opening the command palette (CTRL+SHIFT+P) and then search "hide canvas dots".

Alternatively, could you follow the video at https://github.com/AkshaySG14/haystack-public/issues/14#issuecomment-2325181109?

Apologies for the frustration.

**Comment by coljac** [comment]
> Hmm weird it doesn't work through settings.
> 
> I have a couple of theories. Could you try opening the command palette (CTRL+SHIFT+P) and then search "hide canvas dots".

Dots disappeared, CPU usage did not.

**Comment by clemisch** [comment]
I tried both command palette and developer tools to remove dots. CPU usage is unchanged :-(

**Comment by AkshaySG14** [comment]
Alright I'm going to do a deep dive on this issue tomorrow on a Linux instance. Sorry for the trouble guys.

**Comment by AkshaySG14** [comment]
I believe I have narrowed this issue down to how large the renderer we're using is. Will followup with a solution hopefully soon.

**Comment by AkshaySG14** [comment]
We just published a version on the website that should fix this. I tested it myself, but could someone let me know if this fixes these GPU/CPU issues/

**Comment by coljac** [comment]
> We just published a version on the website that should fix this. I tested it myself, but could someone let me know if this fixes these GPU/CPU issues/

I tested on two machines and the fix seems to be successful, no more CPU pegged at 100%.

**Comment by AkshaySG14** [comment]
Thank you for the quick test. I apologize for taking this long to fix it. Please let me know if y'all see any more issues!

**Comment by clemisch** [comment]
> We just published a version on the website that should fix this. I tested it myself, but could someone let me know if this fixes these GPU/CPU issues/

Indeed, both GPU and CPU load are normal now! Thanks :rocket: 

(on Gnome 46, Wayland, Fedora 40)
