### ISSUE TITLE
Mac ARM M2 without AI navigation bar

### ISSUE THREAD

**Issue by shanxigetanxiaochou** [AkshaySG14/haystack-public#15]
<img width="420" alt="图片" src="https://github.com/user-attachments/assets/ce8d97aa-5e32-49ff-97dc-6fb57d52d35c">

**Comment by AkshaySG14** [comment]
Hi! I cannot quite tell what language this is, but do you have the extension for it installed and is your selection inside a function? E.g. for Java, you need to install the Red Hat Java extension https://marketplace.visualstudio.com/items?itemName=redhat.java and then put your selection inside a method or function.

**Comment by shanxigetanxiaochou** [comment]
Thanks, my local java doesn't seem to work on vscode< following your approach, this has been fixed.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Akshay ***@***.***&gt;; 
发送时间: 2024年8月29日(星期四) 凌晨2:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AkshaySG14/haystack-public] Mac ARM M2 without AI navigation bar (Issue #15)















嗨我不太清楚这是什么语言，但你是否安装了它的扩展，你的选择是否在一个函数内？例如，对于Java，您需要安装Red Hat Java扩展https://marketplace.visualstudio.com/items?itemName=redhat.java然后将您的选择放入方法或函数中。

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.*** &gt;

**Comment by AkshaySG14** [comment]
Going to close this issue since I think it's fixed, but let me know if that's not the case.
