### ISSUE TITLE
commit comment always showed  at top

### ISSUE THREAD

**Issue by rocketlyz** [AkshaySG14/haystack-public#16]
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/dbfcf75d-f59e-487c-be7a-e5201a61b25e">

The cursor is at line 12 (as you see, the commit comment for line 12 showed)，but the top line commit comment showed also.

**Comment by rocketlyz** [comment]
<img width="986" alt="image" src="https://github.com/user-attachments/assets/018893a6-62d6-4099-8c59-0c7c414eeec1">

After I scrolled to some where, these seems placed at the right position

**Comment by AkshaySG14** [comment]
This is a bug with GitLens and is on the list of things to fix!

**Comment by AkshaySG14** [comment]
This should be fixed for GitLens specifically in 0.16. Let me know if that's not the case.
