### ISSUE TITLE
Automatic open editors throw search panel

### ISSUE THREAD

**Issue by yudinmaxim** [AkshaySG14/haystack-public#18]
If you search for a word in the search sidebar, specify what to replace it with, it will be found in several files of the project, and selecting any of the found options will result in nothing happening. It is expected that the editor will open with the file related to the found option, and the cursor will be placed on the line containing the searched word.

**Comment by AkshaySG14** [comment]
Oof this is a bad oversight; will fix ASAP.

**Comment by AkshaySG14** [comment]
This should be fixed in the latest version of Haystack
