### ISSUE TITLE
Haystack copilot configuration 

### ISSUE THREAD

**Issue by bdharris08** [AkshaySG14/haystack-public#2]
Hello! Awesome work here! Are there any plans to support custom configuration for haystack copilot? Some companies require LLM requests to go through company controlled proxies using company issued openAI keys.

Thanks for your consideration.

**Comment by AkshaySG14** [comment]
Yes we definitely intend to support custom config for Haystack's copilot. If you personally have this issue with your company, we'd love to communicate with you more closely!
