### ISSUE TITLE
Middle Mouse Button press bug

### ISSUE THREAD

**Issue by yudinmaxim** [AkshaySG14/haystack-public#21]
**How to reproduce the bug:**
1. Open two editors with text
2. Copy any text to the clipboard
3. Place the cursor in one editor, anywhere
4. Move the mouse pointer to the title of the other editor and click the middle mouse button

**Result:**
1. The editor that was clicked with the middle button closed. This is correct.
2. The copied text was pasted into the editor where the cursor was placed. This is NOT correct.

I am working on Linux, and the 'selection clipboard' parameter is turned off.

**Comment by AkshaySG14** [comment]
Will add to the backlog, although I cannot repro. I'll get to a Linux instance and try.

**Comment by AkshaySG14** [comment]
This should be fixed on v0.18, sorry for the wait!
