### ISSUE TITLE
Unsafe button "Clear all editors in canvas"

### ISSUE THREAD

**Issue by Zmej75** [AkshaySG14/haystack-public#25]
The button does not have a confirmation dialog when you click on it. And, if accidentally pressed, it instantly clears the canvas. The location of the button leads to accidental clicks on it. I have repeatedly lost my configured workspace by accidentally clicking this button.

**Comment by AkshaySG14** [comment]
Will add a dialog for this.

**Comment by Zmej75** [comment]
Thanks! I really appreciated the convenience of working with this editor!

**Comment by AkshaySG14** [comment]
@Zmej75 I like to keep issues open until they're fully fixed just so I can track them!

**Comment by AkshaySG14** [comment]
This should be fixed in the latest version on the website: 0.17! Please let me know if it is not.
