### ISSUE TITLE
"New File..." menu option creates an Editor but doesn't create the file or allow it to be saved

### ISSUE THREAD

**Issue by Dangthrimble** [AkshaySG14/haystack-public#26]
Having created a folder for a new Go project, I opened the Haystack Editor and selected "New File..." from the "File" menu. I named it "main.go" and an Editor was created with that name. However, there was no cursor within that Editor and no line number. Further, the file was not created within the current folder and selecting "Save" from the "File" menu made no difference. 

Haystack Version: 0.16
VS Code Version: 1.90.0
Chromium: 122.0.6261.156
OS: {3 }

<img width="1440" alt="File New  main go" src="https://github.com/user-attachments/assets/6019f58c-5fe1-43bf-8055-11ba2036c8a6">

**Comment by AkshaySG14** [comment]
Hmm this is a regression. Sorry for the trouble and will fix ASAP.

**Comment by AkshaySG14** [comment]
This should be fixed in the latest version on the website: 0.17! Please let me know if it is not.

**Comment by Dangthrimble** [comment]
Looks good to me.

=O)

---- On Wed, 11 Sep 2024 00:54:56 +0000 ***@***.***> wrote ----


This should be fixed in the latest version on the website: 0.17! Please let me know if it is not.
—
Reply to this email directl
