### ISSUE TITLE
[UI] an unnecessary menu item that disrupts the editor's work

### ISSUE THREAD

**Issue by Zmej75** [AkshaySG14/haystack-public#29]
Selecting any of the specified menu items broke the editor. The rest are simply not needed.
![image](https://github.com/user-attachments/assets/86d9e3d7-24a5-408c-b155-b4d9c749214d)
![image](https://github.com/user-attachments/assets/4bd00b42-6048-42ca-9b25-c2c55e2d7612)

**Comment by AkshaySG14** [comment]
Thank you for flagging this. I will remove these menu items.

**Comment by AkshaySG14** [comment]
Removed in 0.18!

**Comment by Zmej75** [comment]
Fixed. I checked it out
