### ISSUE TITLE
Problems with use VSCode extensions:

### ISSUE THREAD

**Issue by Zmej75** [AkshaySG14/haystack-public#30]
Problems with use VSCode extensions:

[HTML Preview](https://marketplace.visualstudio.com/items?itemName=george-alisson.html-preview-vscode)

[Preview](https://marketplace.visualstudio.com/items?itemName=searKing.preview-vscode)

[SQLite Viewer](https://marketplace.visualstudio.com/items?itemName=qwtel.sqlite-viewer)

Nothing happens when the extension is called. When restarting Haystack, an empty editor window and the contents of the extension are displayed outside this window.

[SQLite3 Editor](https://marketplace.visualstudio.com/items?itemName=yy0931.vscode-sqlite3-editor)

When the extension is called, an empty editor window and content outside this window are displayed.

[SQL Notebook](https://marketplace.visualstudio.com/items?itemName=cmoog.sqlnotebook)
It just doesn't work. It doesn't display anything.

[Jupiter](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter)
When starting the cell, it returns an error.

>Haystack Version: 0.17
VS Code Version: 1.90.0
Chromium: 122.0.6261.156
OS: {3 }
![1](https://github.com/user-attachments/assets/a333903b-a62a-48a1-892f-9e5696134a11)
![2](https://github.com/user-attachments/assets/81af58df-8a47-463a-ac7f-6c448aa407e1)
![3](https://github.com/user-attachments/assets/2db7730b-6249-43a8-bd59-6ac405020354)
![4](https://github.com/user-attachments/assets/cc5a6fa1-e90e-4c28-ade8-d8313a3f7c4f)

**Comment by AkshaySG14** [comment]
@Zmej75 These should all be fixed in 0.18. Please let me know if any of these extensions still do not work!

**Comment by Zmej75** [comment]
@AkshaySG14 HTML Preview, Preview, SQLite Viewer, SQLite3 Editor, SQL Notebook - I checked it out. I confirm the working capacity.

**Comment by Zmej75** [comment]
Jupiter - It does not display an interactive window at startup. Incorrect behavior of the viewer extensions may occur after the launch attempt. Returns an error
![2024-09-16_18-47-47](https://github.com/user-attachments/assets/cdec146d-5f43-42e0-b8f8-c04cb2edf893)
