### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by Hawks-Andrew-bah** [AkshaySG14/haystack-public#31]
OS: OSX 14.6.1
Haystack: 0.17

Action: New Terminal 
Behavior: 
- new terminal pane shows, but no text in window. It doesn't seem to spawn the shell process?

Tested with Bash and Zsh. 

Same behavior in regulary VSCode works.

**Comment by AkshaySG14** [comment]
Will take a look ASAP, although I might need to jump in a call with you to repro!

**Comment by Hawks-Andrew-bah** [comment]
I restarted the editor and now it works. So, maybe a fluke.

**Comment by AkshaySG14** [comment]
Let me know if it happens again!
