### ISSUE TITLE
[BUG] Incorrect display of the symbol window after restart Haystack

### ISSUE THREAD

**Issue by Zmej75** [AkshaySG14/haystack-public#32]
I open the symbol in a new window. If I close Haystack after that and reopen it, the symbol window splits into two parts, and a file window, which contains this symbol, appears below it.
all information is in the screenshots
![2024-09-15_09-25-56](https://github.com/user-attachments/assets/e2555838-b41a-480f-b438-b55f378f1bbe)
![2024-09-15_09-28-18](https://github.com/user-attachments/assets/781a9320-f55f-465d-8571-bfc929b81aae)
![2024-09-15_09-32-03](https://github.com/user-attachments/assets/908551a0-eaae-4525-bde7-24d701ef5731)

**Comment by AkshaySG14** [comment]
Will have this fixed in the next day or two!

**Comment by Zmej75** [comment]
Fixed. I checked it out
