### ISSUE TITLE
Resizing pinned window is wonky at different zoom levels

### ISSUE THREAD

**Issue by bvisness** [AkshaySG14/haystack-public#36]
When resizing a pinned window at a zoom level other than 100%, the resizing doesn't match the mouse because the sizing is still being applied as if the window were not pinned.

**Comment by AkshaySG14** [comment]
Will get this fix in by the next release (hopefully soon).

**Comment by AkshaySG14** [comment]
Late but this should be fixed in the latest version of Haystack (0.19).
