### ISSUE TITLE
Saving a new file while pinned un-pins the editor

### ISSUE THREAD

**Issue by bvisness** [AkshaySG14/haystack-public#37]
A minor annoyance to be sure, but when I have a new file opened in a pinned editor, and then save the file, the editor window suddenly un-pins and I have to go find it again.

**Comment by AkshaySG14** [comment]
Hmm I think this bug occurs when the file is renamed as well. Will fix by the next release.

**Comment by AkshaySG14** [comment]
Late but this should be fixed in the latest version of Haystack (0.19).
