### ISSUE TITLE
Git Graph extension view doesn’t appear

### ISSUE THREAD

**Issue by dankinsoid** [AkshaySG14/haystack-public#38]
I use the [Git Graph extension](https://github.com/mhutchie/vscode-git-graph.git), but the graph view doesn't appear in Haystack.

**Steps to reproduce:**
1. Install the Git Graph extension.
2. Open Haystack.
3. Try to access the graph view.

**Expected behavior:**
The Git Graph view should appear in Haystack as it does in other environments.

**Actual behavior:**
The graph view is missing in Haystack.

**Environment:**
- OS: macOS Sonoma 14.6.1
- Haystack Version: 0.17
- Git Graph Version: 1.30.0

**Comment by AkshaySG14** [comment]
Hey! Does downloading the latest version of Haystack off the website (0.18) fix this? I tried it on 0.18 and it should work. Please let me know if you're still having problems after using 0.18!

**Comment by Zmej75** [comment]
in version 0.18, Git Graph works. However, there are overlays of content on the pinned window, as I wrote in #35

**Comment by dankinsoid** [comment]
0.18 works well, thank you!
