### ISSUE TITLE
[BUG] Git 3-way merge editor not displaying correctly

### ISSUE THREAD

**Issue by casrar** [AkshaySG14/haystack-public#39]
When trying to resolve merge conflicts with the built in 3-way editor, the readable area is constrained to a small box and even appears grayed out at times. You are able to "fix" the grayed out window by stretching the bottom pane. But, the window size only ever gets as big as the image below. 

<img width="877" alt="image" src="https://github.com/user-attachments/assets/cf41d586-9b22-45f7-9d84-c234d16190d1">

**Comment by AkshaySG14** [comment]
Ah this is an oversight. Will fix.

**Comment by casrar** [comment]
I'm currently using this as my main editor at work so this has been the only bug so far that's put a major wrench in the works, appreciate you tackling it. Probably gonna make a few feature requests as well at some point!

**Comment by AkshaySG14** [comment]
Would be happy to accommodate! if you haven't already, please join the Discord https://discord.gg/apFrN6ABxc

**Comment by AkshaySG14** [comment]
This should be fixed in the latest version of Haystack on the website!
