### ISSUE TITLE
Using the two column option obliterates the layout

### ISSUE THREAD

**Issue by bvisness** [AkshaySG14/haystack-public#5]
I went to View -> Editor Layout -> Two Columns hoping to get another view into my canvas. Unfortunately it seems like this just totally broke everything, as all the floating windows disappeared and then some started sporadically re-appearing as I moved around. I then reset to one column and everything vanished for good. It seemed to be in a broken state at that point, with new windows not appearing, so I was forced to just restart the whole editor.

**Comment by AkshaySG14** [comment]
This is very unfortunate behavior -- sorry for the frustration. Will add this to the backlog!

**Comment by AkshaySG14** [comment]
The "Editor Layout" menu has been removed, I will add this back later (basically allowing you to have multiple canvases), but I'll close this issue for now.
