### ISSUE TITLE
Using alt-arrows to move lines up and down breaks things

### ISSUE THREAD

**Issue by bvisness** [AkshaySG14/haystack-public#6]
I frequently use alt-up and alt-down to move lines of code up and down. Unfortunately it seems that doing so mangles the current window I'm in, as well as all other windows from the same file.

Since this kind of bug seems to happen somewhat frequently, it would be nice to have a way to "refresh" a window, basically reopening it from the LSP definition. (Edit: As a workaround it seems I can navigate up and down to refresh a window.)

**Comment by AkshaySG14** [comment]
Yeah this seems to completely bork symbol editors. Will fix.

Also I'll add a CMD/CTRL+R to refresh the symbol editor window. Sorry about the trouble!

**Comment by AkshaySG14** [comment]
I believe this is fixed now so closing.
