### ISSUE TITLE
Canvas window management

### ISSUE THREAD

**Issue by nefrob** [AkshaySG14/haystack-public#60]
It would be useful if there were snap hotkeys that have canvas windows jump to fullscreen, left, right, and so on. This would make it feel like the canvases more effectively use the available space when desired.

**Comment by AkshaySG14** [comment]
This is a good idea. Does https://github.com/haystackeditor/haystack-editor/wiki/Roadmap#make-pinned-editors-behave-like-tiled-windows-that-can-be-moved-around-to-occupy-a-portion-of-the-screen fulfill this idea?

**Comment by nefrob** [comment]
@AkshaySG14 yeah that seems like the same idea. Will close this in favor of the roadmap feature. Consider adding custom tile layouts as a longer term featue.
