### ISSUE TITLE
Dependency relationship arrows are not displayed

### ISSUE THREAD

**Issue by akira-toriyama** [AkshaySG14/haystack-public#8]
Thank you for a great app.

Dependency relationship arrows are not displayed.

Have I missed any settings?
Please let me know.

https://github.com/user-attachments/assets/31ca7f9d-1cf9-4e17-8a71-055f119f50e4

https://haystackeditor.com/changelog#:~:text=the%20gif%20below%3A-,Aug%208%2C%202024%20%2D%200.10,-Keyboard%20navigation%2C%20a

**Comment by AkshaySG14** [comment]
Hi Akira!

Sorry this is not straightforward. We only draw arrows between **symbols**, so you need to make the editor a symbol editor. You can do this by using the "view deepest level" button in the floating toolbar.

I've attached a video for you that hopefully makes this clear. 

https://github.com/user-attachments/assets/96c6fca7-b371-4ffc-87e4-5702c89caab7

**Comment by akira-toriyama** [comment]
It worked as expected. 
Thank you very much.
